CC=g++
SRC=GLUT/Source/
OBJ=$(SRC)*.cpp
CFLG= -std=c++11
LIBS= -I /usr/include -lXmu -lglut -lGL -lGLU -lm -lGLEW -lglfw3 -lX11 -lXi -lXrandr -lXxf86vm -lXinerama -lXcursor -lrt -lm -pthread -ldl

all: Main
	
Main:
	$(CC) $(OBJ) $(LIBS) $(CFLG)
	
clean:
	rm a.out